AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template for static website with cloudfront
Parameters:
  SubDomain:
    Description: Type your subdomain
    Type: String
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)

  Hostedzone:
    Description: Select your hosted zone
    Type: AWS::Route53::HostedZone::Id
  
Resources:

  Route53Record:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: "Z2FDTNDATAQYW2"
      HostedZoneId: !Ref Hostedzone
      Name: !Ref SubDomain  # Required
      Type: A # Required

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref SubDomain
        DefaultCacheBehavior:
             AllowedMethods:
                  - GET
                  - HEAD
             Compress: true
             ForwardedValues:
                  QueryString: true
                  Cookies:
                    Forward: none 
             TargetOriginId: kittencouresel
             ViewerProtocolPolicy: allow-all
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        Origins:
           -  CustomOriginConfig: 
                OriginProtocolPolicy: http-only
              DomainName: !GetAtt S3Bucket.DomainName
              Id: kittencouresel
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:071573392472:certificate/7322c871-e81a-4c0f-9e28-29fa63f3b67e
          SslSupportMethod: sni-only
  
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket # Required
      PolicyDocument:  # Required
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Principal: '*'
            Sid: PublicReadGetObject
            Resource: !Join ['', ['arn:aws:s3:::', !Ref 'S3Bucket', /*]]
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref SubDomain
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
      WebsiteConfiguration:
        IndexDocument: index.html

Outputs:
  Bucketurl:
    Description: This is bucket weburl
    Value: !GetAtt S3Bucket.WebsiteURL

  FrontDns:
    Description: this is cloudfront domain name
    Value: !GetAtt CloudFrontDistribution.DomainName

  DNS:
    Description: This is my subdomain
    Value: !Ref SubDomain
